Add output_of class method that gives the return value of actor's #call
sunny/actor pull request #152
Opened 2024-04-10 15:37 UTC by llhhaa

As proposed in #151, this implements an `output_of` class method on actors. It returns the value of the actor's `call` method, or in the case of play actors, returns the value of the final actor's `call`. it otherwise functions exactly the same, respecting play conditions, validations, raising `ServiceActor::Failure` when an actor fails, etc.

```ruby
> IncrementValue.call(value: 1)
=> <ServiceActor::Result { :value => 2 }>

> IncrementValue.output_of(value: 1)
=> 2
```

This works by assigning the result of `call` to an internal result data key, `:_default_output`, then accessing that key for the return value. Because it is an internal key, I chose to filter it from `Result#to_h` so it is not visible to end users, though it is still technically there and accessible if you know about it.

I had to update the `_call` overrides of some of the feature concerns (`Checkable`, `Playable`) to maintain the return value chain of `super`, but the existing return values were not being used for anything.

I think the only addition might be support for returning the last rollback value, if desired. `Actor.result` allows access to the results of failed actors or play actor chains. Since `output_of` is more akin to `call` and raises when an actor in a play/rollback chain fails, one could add an option to not raise but instead return the last valid rollback value in the actor chain.

2024-04-10 19:01 UTC, sunny requested changes
That looks great, actually. I'd be happy to add it now after these suggestions.

Also, can you include an update to the README (although it's getting a bit too long for my liking...) and to the CHANGELOG ?

2024-04-10 21:32 UTC, llhhaa commented on lib/service_actor/outputable.rb
> +    def output_of(result = nil, **arguments)
Agreed, I was mulling over whether this was the best name. My concern with `.output()` was name collision with `ServiceActor::Attributable.output()`, I'm pretty sure that takes that option off the table.

Other options might be:
```
.get()
.retrieve()
.return()
.yield()
.value()
```

2024-04-10 21:44 UTC, llhhaa commented on lib/service_actor/result.rb
> +    h.filter { |k| k != :_default_output }
It looks like this does break compatibility with Ruby 2.7. Would you prefer I stick with `filter`?

2024-04-10 21:50 UTC, llhhaa commented
@sunny Added README and CHANGELOG updates. Just need to settle on a name for the method and decide about `Hash#except`.

2024-04-11 08:11 UTC, sunny commented on lib/service_actor/outputable.rb
> +    def output_of(result = nil, **arguments)
I’m leaning towards `.value()` as it hints at the fact that there is only one thing returned.

That sounds Valuable 😬

2024-04-11 08:14 UTC, sunny commented on lib/service_actor/result.rb
> +    h.filter { |k| k != :_default_output }
Oh, forgot that this was new!

Perhaps we can do both with a `h.respond_to?(:except)` and a small comment to remind us that this is only for Ruby 2.7 compatibility? That’ll be a good reminder to clean it up later.

2024-04-11 13:03 UTC, llhhaa commented on lib/service_actor/outputable.rb
> +    def output_of(result = nil, **arguments)
Rename complete. Let me know if you like how `.value()` reads.

2024-04-12 18:04 UTC, sunny approved these changes
Valuable addition, thank you 👏🏻

2024-04-12 18:04 UTC, merged